export const STORE_DATA = [
  { code: "G001", name: "갤러리아 본점" },
  { code: "H0001", name: "현대백화점 목동점" },
  { code: "M0001", name: "신세계 강남점" },
  { code: "M0002", name: "신세계 본점" },
  { code: "M0003", name: "신세계 사우스시티점" },
  { code: "M0004", name: "신세계 김해점" },
  { code: "M0005", name: "신세계 대구점" },
  { code: "M0006", name: "신세계 마산점" },
  { code: "M0007", name: "신세계 센텀점" },
  { code: "M0008", name: "신세계 타임스퀘어점" },
  { code: "M0009", name: "신세계 의정부점" },
  { code: "M0010", name: "신세계 천안아산점" },
  { code: "M0011", name: "신세계 하남점" },
  { code: "M0012", name: "현대백화점 본점" },
  { code: "M0013", name: "현대판교점" },
  { code: "M0014", name: "롯데본점" },
  { code: "M0015", name: "(DJI)롯데백화점 잠실점" },
  { code: "M0016", name: "신세계 광주점" },
  { code: "M0017", name: "롯데마트" },
  { code: "M0018", name: "제이앤피(J&P)" },
  { code: "M0019", name: "갤러리아광교점" },
  { code: "M0020", name: "AK분당점(J&P)" },
  { code: "M0021", name: "LF라움" },
  { code: "M0022", name: "코스트코양재" },
  { code: "M0023", name: "코스트코광명" },
  { code: "M0024", name: "코스트코상봉" },
  { code: "M0025", name: "게이즈샵" },
  { code: "M0026", name: "분더샵" },
  { code: "M0027", name: "롯데인천점" },
  { code: "M0029", name: "갤러리아타임월드(J&P)" },
  { code: "M0030", name: "롯데영등포점(SPC)" },
  { code: "M0031", name: "(DJI)롯데백화점 부산본점" },
  { code: "M0032", name: "AK수원점(J&P)" },
  { code: "M0033", name: "롯데대구점(SPC)" },
  { code: "M0034", name: "현대킨텍스점" },
  { code: "M0035", name: "롯데광복점(SPC)" },
  { code: "M0036", name: "롯데센텀점(SPC)" },
  { code: "M0037", name: "롯데창원점(SPC)" },
  { code: "M0038", name: "코스트코공세" },
  { code: "M0039", name: "한샘(잠실점)" },
  { code: "M0040", name: "(DJI)현대백화점 무역점" },
  { code: "M0041", name: "코스트코일산" },
  { code: "M0042", name: "코스트코세종" },
  { code: "M0043", name: "린나이플러스" },
  { code: "M0044", name: "코스트코하남" },
  { code: "M0045", name: "코스트코의정부" },
  { code: "M0046", name: "코스모앤컴퍼니" },
  { code: "M0047", name: "롯데분당점" },
  { code: "M0048", name: "트레이더스 위례점" },
  { code: "M0049", name: "라이프비" },
  { code: "M0050", name: "코스트코송도" },
  { code: "M0051", name: "코스트코광명(사용안함)" },
  { code: "M0052", name: "현대백화점 중동점" },
  { code: "M0053", name: "큐레이션A WHOLESALE" },
  { code: "M0054", name: "신세계 대전 아트앤싸이언스점" },
  { code: "M0055", name: "현대천호점" },
  { code: "M0056", name: "롯데백화점 평촌점" },
  { code: "M0057", name: "현대백화점 더현대서울" },
  { code: "M0058", name: "롯데백화점 강남" },
  { code: "M0059", name: "(DJI)롯데백화점 동탄점" },
  { code: "M0060", name: "(DJI)신세계백화점 대전점" },
  { code: "M0061", name: "현대백화점 신촌점" },
  { code: "M0062", name: "현대백화점 울산점" },
  { code: "M0063", name: "(DJI)신세계백화점 사우스시티점" },
  { code: "M0064", name: "(DJI)롯데백화점 인천점" },
  { code: "M0065", name: "(DJI)스타필드 수원점" },
  { code: "M0066", name: "(DJI)신세계백화점 본점" },
  { code: "M0067", name: "(DJI)신세계백화점 대구점" },
  { code: "M0068", name: "(DJI)롯데백화점 본점" },
  { code: "M0069", name: "(DJI)신세계백화점 센텀시티점" },
  { code: "M0070", name: "(DJI)신세계백화점 광주점" },
  { code: "M0071", name: "(DJI)현대백화점 판교점" },
  { code: "M0072", name: "(DJI)현대백화점 킨텍스점" },
  { code: "M0073", name: "(DJI)부띠끄 강남" },
  { code: "M0074", name: "(DJI)현대백화점 더현대서울" },
  { code: "M0075", name: "(DJI)신세계백화점 강남" },
  { code: "M0076", name: "(DJI)현대백화점 압구정본점" },
  { code: "M0077", name: "(DJI)현대 면세점" },
  { code: "M0078", name: "(DJI)신라 면세점" },
  { code: "M0079", name: "(DJI)신세계 면세점" },
  { code: "M0080", name: "(DJI)부띠끄 일산" },
  { code: "M0081", name: "(DJI)현대백화점 더현대 대구점" },
  { code: "M0082", name: "(핫셀)신세계백화점 강남" },
  { code: "M0083", name: "현대백화점 미아점" },
  { code: "M0084", name: "(DJI)갤러리아 광교점" },
  { code: "M0085", name: "신세계 청담점" },
  { code: "N0001", name: "마이분" },
  { code: "ON001", name: "온라인몰(소형)" },
  { code: "ON002", name: "온라인몰(소형제외)" },
] as const;
